function AISummary({ summary, onReset }) {
  // Split bullet points — handles both • and * and \n
  const bullets = summary
    .split(/\n/)
    .map(line => line.replace(/^[\*\•\-]\s*/, "").trim())
    .filter(line => line.length > 0);

  return (
    <div className="bg-slate-800 border border-sky-800 rounded-xl p-5 mb-6">

      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <span className="text-lg">✨</span>
          <h3 className="text-sky-400 font-semibold text-sm">AI Summary</h3>
        </div>
        <button
          onClick={onReset}
          className="text-slate-500 hover:text-slate-300 text-xs transition-colors"
        >
          Hide
        </button>
      </div>

      {/* Bullet Points */}
      <ul className="space-y-3">
        {bullets.map((point, i) => (
          <li key={i} className="flex items-start gap-3">
            <span className="text-sky-400 font-bold mt-0.5 flex-shrink-0">
              {i + 1}.
            </span>
            <span className="text-slate-300 text-sm leading-relaxed">
              {point}
            </span>
          </li>
        ))}
      </ul>

      {/* Footer */}
      <p className="text-slate-600 text-xs mt-4 pt-3 border-t border-slate-700">
        Generated by Groq AI — may not reflect full article
      </p>

    </div>
  );
}

export default AISummary;